on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Print hello
        shell: bash
        run: echo "hello ${{ secrets.GH_USERNAME }}"
