on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        shell: bash
        run: |
          echo "NAME= Nguyen Dac Long" >> $GITHUB_ENV
          echo "Mó nìn $NAME"
 
