name: hello
on:
  schedule:
    - cron: "0/10 * * * *"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "NAME= Mực" >> $GITHUB_ENV
      - run: echo "TODAY=$(date +%d/%m/%y)" >>  $GITHUB_ENV
      - run: echo "Mó nìn $NAME, hum ni là $TODAY"
 
