on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "NAME= Nguyen Dac Long" >> $GITHUB_ENV
      - run: echo "Mó nìn $NAME"
 
