name: hello
on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "NAME= Mực" >> $GITHUB_ENV
      - run: echo "TODAY=$(date +ngày %d tháng %m năm %y)" >>  $GITHUB_ENV
      - run: echo "Mó nìn $NAME, hum ni là $TODAY"
 
