name: Dảk
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  AWS:
    runs-on: ubuntu-latest
    steps:
      - name: Cho biết vị trí hiện thư mục hiện tại đang làm việc.
        run: pwd
      - name: Liệt kê toàn bộ các file đang có tại ví trí đó.
        run: ls -a
      - name: Liệt kê toàn bộ biến môi trường (bao gồm cả hệ thống).
        run: printenv
