name: Dảk
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  AWS:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          pwd
          ls -a
