name: Dảk
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  AWS:
    runs-on: ubuntu-latest
    steps:
      - name: Cho biết vị trí hiện thư mục hiện tại đang làm việc.
        run: pwd
      - name: Liệt kê toàn bộ các file đang có tại ví trí đó.
        run: ls -a
      - name: Liệt kê toàn bộ biến môi trường (bao gồm cả hệ thống).
        run: printenv
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Show bucket s3
        run: aws s3 ls
      - name: Docker
        run: |
          sudo apt-get update
          sudo apt-get install \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
