name: Hello NAME
on:
  schedule:
    - cron: "0/10 * * * *"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "NAME=Long đẹp trai" >> $GITHUB_ENV
          echo "TODAY=$(date +%d/%m/%y %H:%M:%S)" >>  $GITHUB_ENV
          echo "Hé lồ anh $NAME, bây chừ là $TODAY, nghỉ thôi chứ làm gì nữa"
 
